# Heart Disease Prediction

Data Source: https://www.kaggle.com/ronitf/heart-disease-uci/downloads/heart-disease-uci.zip/1

In [4]:
#libraries for loading data from kaggle
import csv
import requests
import openpyxl
import pandas as pd

#libraries for model
import pandas as pd 
import numpy as np

# Import Data

In [5]:
heart_data = pd.read_csv('../data/heart.csv')

In [6]:
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

# EDA

#### 303 patients

In [7]:
len(heart_data)

303

# Model Development

In [8]:
x = heart_data.iloc[:, :-1].values
y = heart_data.iloc[:, 13].values

In [16]:
#x

In [17]:
#y

#### Create CV indicies

In [18]:
import numpy as np
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [26]:
#len(X_train)

In [27]:
#len(X_test)

In [28]:
#y_train

In [29]:
#y_test

In [31]:
# Missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 0:13])
x[:, 0:13] = imputer.transform(x[:, 0:13])

/Users/naomi/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [32]:
x

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [38]:
# validate there are no more NaN values in data, and they have been replaced by 0
#sum(np.isnan(x)==True)

In [39]:
#TEST
imputer_test = imputer.fit(x_test[:,:])
x_test[:,:] = imputer_test.transform(x_test[:,:])


In [40]:
x_test

array([[57.,  1.,  0., ...,  1.,  1.,  1.],
       [59.,  1.,  3., ...,  1.,  0.,  3.],
       [57.,  1.,  2., ...,  2.,  1.,  3.],
       ...,
       [52.,  1.,  0., ...,  2.,  3.,  3.],
       [44.,  1.,  1., ...,  2.,  0.,  2.],
       [64.,  1.,  2., ...,  1.,  0.,  3.]])

In [43]:
#Feature Scaling to mean center
from sklearn.preprocessing import StandardScaler as ss
sc = ss()
x = sc.fit_transform(x)
x_test = sc.fit_transform(x_test)


In [48]:
#x_test

In [45]:
x_train = sc.fit_transform(x_train)
#X_test = sc.transform(X_test)

In [47]:
#x_train

In [49]:

# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x, y)
#classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [50]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)

In [51]:
y_pred

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0])

# Testing

In [52]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[39  3]
 [ 4 54]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92        42
           1       0.95      0.93      0.94        58

   micro avg       0.93      0.93      0.93       100
   macro avg       0.93      0.93      0.93       100
weighted avg       0.93      0.93      0.93       100

